# Generated by Django 5.1.6 on 2025-02-13 17:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apis', '0002_customuser_statut'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customuser',
            name='statut',
        ),
        migrations.AddField(
            model_name='task',
            name='statut',
            field=models.BooleanField(default=False),
        ),
    ]
